const CONFIG={rooms:['8318','8319'],open:9,close:22,maxMinutes:180,tz:'Asia/Seoul',sheetName:'예약API'};
const HEADERS=['예약번호','프로젝트실','시작','종료','예약자','학번','용도','메모','PIN해시','상태','이벤트ID','생성일시','취소일시'];
const PURPOSES=['학과 회의','수업/세미나','학생 모임','상담/면담','프로젝트','면접','기타'];
function doGet(e){try{const a=e.parameter.action||'health';if(a==='getReservations')return out({ok:true,reservations:getReservations_(e.parameter.date)});if(a==='checkAvailability')return out(checkAvailability_(e.parameter));return out({ok:true,service:'meeting-room-api',rooms:CONFIG.rooms})}catch(err){return out({ok:false,error:err.message})}}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}'),a=b.action;if(a==='createReservation')return out({ok:true,...createReservation_(b)});if(a==='findReservation')return out({ok:true,reservations:findReservation_(b)});if(a==='cancelReservation')return out({ok:true,...cancelReservation_(b)});throw Error('지원하지 않는 요청입니다.')}catch(err){return out({ok:false,error:err.message})}}
function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function ss_(){const p=PropertiesService.getScriptProperties(),id=p.getProperty('SHEET_ID');if(!id)throw Error('SHEET_ID가 설정되지 않았습니다.');const book=SpreadsheetApp.openById(id);let s=book.getSheetByName(CONFIG.sheetName);if(!s)s=book.insertSheet(CONFIG.sheetName);if(s.getLastRow()===0)s.appendRow(HEADERS);return s}
function rows_(){const s=ss_(),v=s.getDataRange().getValues();return v.slice(1).filter(r=>r[0]).map(r=>({id:String(r[0]),room:String(r[1]),start:r[2] instanceof Date?r[2]:new Date(r[2]),end:r[3] instanceof Date?r[3]:new Date(r[3]),name:String(r[4]),studentId:String(r[5]),purpose:String(r[6]),memo:String(r[7]),hash:String(r[8]),status:String(r[9]),eventId:String(r[10])}))}
function parse_(date,time){const a=String(date).match(/^(\d{4})-(\d{2})-(\d{2})$/),b=String(time).match(/^(\d{2}):(\d{2})$/);if(!a||!b)throw Error('날짜 또는 시간이 올바르지 않습니다.');return new Date(Number(a[1]),Number(a[2])-1,Number(a[3]),Number(b[1]),Number(b[2]),0)}
function validate_(d){if(!CONFIG.rooms.includes(String(d.room)))throw Error('프로젝트실을 확인하세요.');if(!d.name||!d.studentId||!d.pin||!/^[0-9]{4}$/.test(String(d.pin)))throw Error('이름, 학번, 4자리 PIN을 확인하세요.');if(!PURPOSES.includes(String(d.purpose)))throw Error('사용 용도를 확인하세요.');const s=parse_(d.date,d.start),e=parse_(d.date,d.end),now=new Date();if(s<now)throw Error('지난 시간은 예약할 수 없습니다.');if(s.getHours()<CONFIG.open||e.getHours()>CONFIG.close||e<=s)throw Error('운영시간 또는 시간 범위를 확인하세요.');if((e-s)/60000>CONFIG.maxMinutes)throw Error('최대 3시간까지 예약할 수 있습니다.');return {s,e}}
function overlap_(a,b,c,d){return a<d&&c<b}
function checkAvailability_(d){if(!CONFIG.rooms.includes(String(d.room)))throw Error('프로젝트실을 확인하세요.');const s=parse_(d.date,d.start),e=parse_(d.date,d.end);const busy=rows_().some(r=>r.room===String(d.room)&&r.status==='ACTIVE'&&overlap_(s,e,r.start,r.end));return {available:!busy,room:String(d.room),date:d.date,start:d.start,end:d.end}}
function secret_(){const p=PropertiesService.getScriptProperties();let s=p.getProperty('PIN_SECRET');if(!s){s=Utilities.getUuid();p.setProperty('PIN_SECRET',s)}return s}
function hash_(student,pin){return Utilities.base64Encode(Utilities.computeHmacSha256Signature(String(student)+'|'+String(pin),secret_()))}
function id_(){return 'MR-'+Utilities.formatDate(new Date(),CONFIG.tz,'yyyyMMddHHmmss')+'-'+Math.floor(Math.random()*900+100)}
function createReservation_(d){const x=validate_(d),lock=LockService.getScriptLock();lock.waitLock(15000);try{const duplicate=rows_().find(r=>r.status==='ACTIVE'&&r.room===String(d.room)&&r.studentId===String(d.studentId)&&r.start.getTime()===x.s.getTime()&&r.end.getTime()===x.e.getTime());if(duplicate)return {reservationId:duplicate.id,room:duplicate.room,start:duplicate.start.toISOString(),end:duplicate.end.toISOString(),duplicate:true};const conflict=checkAvailability_({...d,start:d.start,end:d.end});if(!conflict.available)throw Error('선택한 시간에 이미 예약이 있습니다.');const id=id_(),calId=PropertiesService.getScriptProperties().getProperty('CAL_'+d.room),cal=calId?CalendarApp.getCalendarById(calId):null;let eventId='';if(cal){const ev=cal.createEvent('프로젝트실 '+d.room+' · '+d.purpose,x.s,x.e,{description:'예약번호: '+id+'\n메모: '+(d.memo||'')});eventId=ev.getId()}ss_().appendRow([id,d.room,x.s,x.e,d.name,String(d.studentId),d.purpose,d.memo||'',hash_(d.studentId,d.pin),'ACTIVE',eventId,new Date(),'']);return {reservationId:id,room:d.room,start:x.s.toISOString(),end:x.e.toISOString()}}finally{lock.releaseLock()}}
function mask_(n){n=String(n);return n.length<2?'*':n[0]+'*'.repeat(Math.max(1,n.length-2))+n[n.length-1]}
function getReservations_(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(date)))throw Error('날짜를 확인하세요.');const a=parse_(date,'00:00'),b=parse_(date,'23:59');return rows_().filter(r=>r.status==='ACTIVE'&&overlap_(a,b,r.start,r.end)).map(r=>({reservationId:r.id,room:r.room,start:r.start.toISOString(),end:r.end.toISOString(),name:r.name,purpose:r.purpose,memo:r.memo}))}
function findReservation_(d){if(!d.studentId||!d.pin)throw Error('학번과 PIN을 입력하세요.');return rows_().filter(r=>r.studentId===String(d.studentId)&&r.hash===hash_(d.studentId,d.pin)).map(r=>({reservationId:r.id,room:r.room,start:r.start.toISOString(),end:r.end.toISOString(),purpose:r.purpose,memo:r.memo,status:r.status}))}
function cancelReservation_(d){if(!d.reservationId||!d.studentId||!d.pin)throw Error('예약번호, 학번, PIN이 필요합니다.');const s=ss_(),v=s.getDataRange().getValues();for(let i=1;i<v.length;i++){if(String(v[i][0])===String(d.reservationId)&&String(v[i][5])===String(d.studentId)&&String(v[i][8])===hash_(d.studentId,d.pin)){if(String(v[i][9])!=='ACTIVE')throw Error('이미 취소된 예약입니다.');if(v[i][10]){const c=CalendarApp.getEventById(String(v[i][10]));if(c)c.deleteEvent()}s.getRange(i+1,10).setValue('CANCELLED');s.getRange(i+1,13).setValue(new Date());return {cancelled:true}}}throw Error('예약을 찾지 못했습니다.')}
function initializeSystem(){ss_();secret_();return '예약API 시트와 PIN 설정 완료'}
